### ISSUE TITLE
Dub build fails with -version=0.4.0 switch 

### ISSUE THREAD

**Issue by growlercab** [Dgame/Dgame#24]
I am on Arch linux x86_64 using DMD 2.066.1

When building a Dgame app with dub I get the following error:

Error: unrecognized switch '-version=0.4.0'

**Comment by growlercab** [comment]
I don't think DMD supports 0.4.0 as a version identifier. It supports integers and named versions but not "floating point".

After a quick grep I noticed this isn't used in Dgame sources so I assume it was just a simple mistake in the dub.json.

If I remove the "versions":"0.4.0" from the dub.json it builds OK so I'll submit a PR with this removed.

**Comment by growlercab** [comment]
OK I've submitted a PR testing on Arch and it seems to work OK.

I find it really hard to extract relevant information from the DUB docs but once it's up and working DUB is very nice to use.

**Comment by Dgame** [comment]
I merged the PR, so this should be resolved.

**Comment by growlercab** [comment]
Cool, thanks! 

I just tried a blank dub build and the package pulled in from http://code.dlang.org/ doesn't have the latest changes.

Sorry I don't know how the DUB registry works as I've never put anything up before. I believe it uses git version tags to automatically track updates. If so you may need to bump the tag version number.

**Comment by Dgame** [comment]
I have also no clue how do it. I will read the manual and try to figure it out, but maybe @aldacron knows how to do it?

**Comment by growlercab** [comment]
I think you just need to tag again. You can delete tags if you want to keep the 0.4.0 version number but it is probably easier just to do a 0.4.1 release in github. DUB should then pick up the new tag and show that as the latest in the registry.

But I've never actually done this so it is best to ask aldacron to be sure :-)

**Comment by aldacron** [comment]
Yeah, go ahead and tag 0.4.1. The DUB registry will eventually pick it up. You can speed things along by logging in to the registry, selecting your Dgame package, and clicking the 'Trigger Manual Update' button. If it's grayed out, that means Dgame is already scheduled for an update. Users who have already pulled it down through DUB can then run 'dub upgrade' to get it.

**Comment by Dgame** [comment]
All right, thank you both.
