### ISSUE TITLE
Setting OpenGL version needs to be before window creation

### ISSUE THREAD

**Issue by MatthewFrench** [Dgame/Dgame#27]
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
			SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
			SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
			SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);

They are after window creation.

**Comment by Dgame** [comment]
Should be fixed. New tag is published, Manual update is triggered on DUB.
