### ISSUE TITLE
Error when running 0.5 beta test

### ISSUE THREAD

**Issue by MatthewFrench** [Dgame/Dgame#30]
../Audio/Sound.d(90): Error: @nogc function 'Dgame.Audio.Sound.Sound.loadFromFile' cannot call non-@nogc function 'derelict.sdl2.mixer.Mix_LoadWAV'
../System/Font.d(172): Error: @nogc function 'Dgame.System.Font.Font.render!().render' cannot call non-@nogc function pointer 'TTF_RenderUTF8_Solid'
../System/Font.d(175): Error: @nogc function 'Dgame.System.Font.Font.render!().render' cannot call non-@nogc function pointer 'TTF_RenderUTF8_Shaded'
../System/Font.d(178): Error: @nogc function 'Dgame.System.Font.Font.render!().render' cannot call non-@nogc function pointer 'TTF_RenderUTF8_Blended'
../Graphic/Text.d(68): Error: template instance Dgame.System.Font.Font.render!() error instantiating
../Graphic/Texture.d(469): Error: no property 'getFormat' for type 'const(Texture)'
../System/Font.d(105): Error: @nogc function 'Dgame.System.Font.Font.~this' cannot call non-@nogc function pointer 'TTF_CloseFont'
../System/Font.d(120): Error: @nogc function 'Dgame.System.Font.Font.loadFromFile' cannot call non-@nogc function pointer 'TTF_OpenFont'
../System/Font.d(137): Error: @nogc function 'Dgame.System.Font.Font.setStyle' cannot call non-@nogc function pointer 'TTF_SetFontStyle'
../System/Font.d(148): Error: @nogc function 'Dgame.System.Font.Font.getStyle' cannot call non-@nogc function pointer 'TTF_GetFontStyle'
../Window/Window.d(374): Error: @nogc function 'Dgame.Window.Window.Window.hasQuitEvent' cannot call non-@nogc function 'derelict.sdl2.functions.SDL_QuitRequested'
main.d(66): Error: no property 'getFormat' for type 'Texture'
FAIL .dub/build/main-debug-posix.osx-x86_64-dmd_2066-475D155ABBFA067E77BD70242FDF64AE/ dgame-example executable
Error executing command run: dmd failed with exit code 1.

**Comment by Dgame** [comment]
I know that. It's because derelict has many functions which should be @nogc but currently aren't. But aldacron will fix this soon.

**Comment by Dgame** [comment]
See: https://github.com/DerelictOrg/DerelictSDL2/issues/39

**Comment by Dgame** [comment]
@MatthewFrench I've overlooked the last one:
>main.d(66): Error: no property 'getFormat' for type 'Texture'
FAIL .dub/build/main-debug-posix.osx-x86_64-dmd_2066-475D155ABBFA067E77BD70242FDF64AE/ dgame-example executable

That's indeed my mistake. Fixed in 2c17474dbb65674075c511611f332548c4c2dad6

**Comment by Dgame** [comment]
Fixed
