### ISSUE TITLE
Weird text issue

### ISSUE THREAD

**Issue by MatthewFrench** [Dgame/Dgame#31]
Text seems to stretch given enough time. Here's a few pictures.

http://cl.ly/image/0l2i061y2t0M
http://cl.ly/image/200h3W02012d
http://cl.ly/image/1J0G2g2T3a2U

**Comment by Dgame** [comment]
Looks strange. Which OS?

**Comment by Dgame** [comment]
Should be fixed.

**Comment by Dgame** [comment]
@MatthewFrench can you confirm?
