### ISSUE TITLE
Error in dub.json on ~0.5.0 branch

### ISSUE THREAD

**Issue by growlercab** [Dgame/Dgame#32]
When I try to build any app using Dgame 0.5.0 I get this error message:

> Failed to parse package description for dgame ~0.5.0 in remote location.
> Package dgame ~0.5.0 could not be loaded either locally, or from the configured package registries.
> Fetching dgame ~0.5.0 (getting selected version)...
> Placing dgame ~0.5.0 to $HOME/.dub/packages/...
> Failed to parse package description for dgame ~0.5.0 in $HOME/.dub/packages/dgame-0.5.0.
> Error executing command build:
> TargetType does not have a member named 'lib'

Looking at the dub.json, the `"targetType"` needs to be either `"sourceLibrary"` or just `"library"` but not `"lib"`.

**Comment by growlercab** [comment]
I might be all wrong about this because you're clearly building on this branch. Maybe my dub is out of date (it's Feb 17 2015)? 

If so feel free to close this and I'll figure out what I'm doing wrong.

**Comment by Dgame** [comment]
Currently, I'm using the test directory only, so it could be my fault. I will change it to 'library'.

**Comment by Dgame** [comment]
I believe 'library' could bring some trouble since Dgame isn't like other DUB packages; there is no src/Dgame path. If 'sourceLibrary' works better than 'library, I have to change the structure to src/Dgame.

**Comment by growlercab** [comment]
Thanks, I'll give it a try.

I think `sourceLibrary` should work OK because you have `"sourcePaths":["."]` in your dub.json.

**Comment by growlercab** [comment]
OK, the dub.json bug is now fixed  but as a library target it fails because it picks up main() in test/main.d and I get this error.

` ../../../../.dub/packages/dgame-0.5.0/test/main.d(35): Error: only one main allowed`

The fix  is trivial and requires changing the "excludedSourceFiles" field in the "lib" target to:

`"excludedSourceFiles": ["main.d", "test/main.d"]`. 

Whenever you around to this is cool, 0.5.0 is WIP after all. 
(sorry I cannot do a PR for this, I don't have access to a build machine for a few days.)

**Comment by Dgame** [comment]
After tomorrow I have plenty of time. ;) But I will fix this small bug in the next hour.
How do you import Dgame if you build it as a library?

**Comment by growlercab** [comment]
Ah, sorry my bad. When I look now I see that I had Dgame building as a sourceLibrary.

WIth the last commit and Dgame targetType as sourceLibrary I can compile and run the "tut.d" as a completely separate dub project.
_(I get a run time error from Derelict about invalid fonts but that is unrelated to this issue)_

Build with Dgame as a "library" target I get the import path error:
> source/testdgame.d(4): Error: module Window is in file 'Dgame/Window/Window.d' which cannot be read

Sorry for the confusion. If I figure out a way to convince dub to apply a Dgame prefix to the required import paths I'll let you know.

**Comment by Dgame** [comment]
The whole test folder will disappear, so it's only a temporal fix. ;) Don't worry.

> source/testdgame.d(4): Error: module Window is in file 'Dgame/Window/Window.d' which cannot be read

It's because Dgame is not built like DUB wants to. Maybe I should change it to 'source/Dgame'. DUB will automatically accept source as import path and the error should disappear.
