### ISSUE TITLE
General errors

### ISSUE THREAD

**Issue by joelcnz** [Dgame/Dgame#34]
[1] - see bottom

C:\jpro\dpro2\OtherPeoples\Dgame>dub
Building dgame 0.5.0-beta.2+commit.1.gd66bf03 configuration "lib", build type de
bug.
Running dmd...
4u
16u
64u
72u
4u
20u
8u
8u
32u
source\Dgame\Graphic\Surface.d(180): Error: @nogc function 'Dgame.Graphic.Surfac
e.Surface.loadFromFile' cannot call non-@nogc function 'std.file.exists'
source\Dgame\Graphic\Surface.d(180): Error: 'std.file.exists' is not nothrow
source\Dgame\Graphic\Surface.d(177): Error: function 'Dgame.Graphic.Surface.Surf
ace.loadFromFile' is nothrow yet may throw
source\Dgame\Graphic\Surface.d(608): Error: function Dgame.Math.Rect._transfer i
s not accessible from module Surface
source\Dgame\Graphic\Surface.d(609): Error: function Dgame.Math.Rect._transfer i
s not accessible from module Surface
source\Dgame\Graphic\Surface.d(633): Error: function Dgame.Math.Rect._transfer i
s not accessible from module Surface
source\Dgame\Graphic\Surface.d(634): Error: function Dgame.Math.Rect._transfer i
s not accessible from module Surface
source\Dgame\System\Font.d(170): Error: module Dgame.System.Font function Dgame.
Graphic.Color._transfer is private
source\Dgame\System\Font.d(170): Error: function Dgame.Graphic.Color._transfer i
s not accessible from module Font
source\Dgame\System\Font.d(171): Error: module Dgame.System.Font function Dgame.
Graphic.Color._transfer is private
source\Dgame\System\Font.d(171): Error: function Dgame.Graphic.Color._transfer i
s not accessible from module Font
source\Dgame\Graphic\Text.d(67): Error: template instance Dgame.System.Font.Font
.render!() error instantiating
source\Dgame\Window\Window.d(145): Error: module Dgame.Window.Window function Dg
ame.Window.Internal.Init._initSDL is private
source\Dgame\Window\Window.d(145): Error: function Dgame.Window.Internal.Init._i
nitSDL is not accessible from module Window
source\Dgame\Window\Window.d(148): Error: module Dgame.Window.Window function Dg
ame.Window.Internal.Init._initGLAttr is private
source\Dgame\Window\Window.d(148): Error: function Dgame.Window.Internal.Init._i
nitGLAttr is not accessible from module Window
source\Dgame\Window\Window.d(159): Error: module Dgame.Window.Window function Dg
ame.Window.Internal.Init._initGL is private
source\Dgame\Window\Window.d(159): Error: function Dgame.Window.Internal.Init._i
nitGL is not accessible from module Window
source\Dgame\Window\Window.d(125): Error: template instance Dgame.Window.Window.
Window.__ctor!() error instantiating
FAIL .dub\build\lib-debug-windows-x86-dmd_2066-7A96EE8F0A68A2410292AA6D54ADEF4C\
 Dgame staticLibrary
Error executing command run: dmd failed with exit code 1.

[1] After I've commented out the 3 similar lines in three eg "package(Dgame.Window):"

**Comment by joelcnz** [comment]
Oh, maybe this issue isn't useful. I think some body else posted a similar post, and it's being worked out.

**Comment by Dgame** [comment]
Yes, it's because I've used the 2.067 version to built. I'm on it.
