### ISSUE TITLE
Trying to modify const variables

### ISSUE THREAD

**Issue by joelcnz** [Dgame/Dgame#35]
source/Dgame/Window/Internal/Init.d(130): Error: cannot modify const expression gl_settings.majorVersion
source/Dgame/Window/Internal/Init.d(131): Error: cannot modify const expression gl_settings.minorVersion

I took the const out, and it all went through.

**Comment by Dgame** [comment]
That is the problem, if you don't have a Mac. ;)

**Comment by Dgame** [comment]
I've updated the v0.5.0-beta.3 tag.

**Comment by joelcnz** [comment]
I can compile the library now, but I'm stuck again:

Joels-MacBook-Pro:test joelcnz$ ls
SDL2.dll        libjpeg-9.dll        libvorbis.dll
SDL2_image.dll        libmikmod-2.dll        libvorbisfile-3.dll
SDL2_mixer.dll        libmodplug-1.dll    libvorbisfile.dll
SDL2_ttf.dll        libogg-0.dll        libwebp-4.dll
cmd.lnk            libogg.dll        main.d
dub.json        libpng16-16.dll        samples
libFLAC-8.dll        libtiff-5.dll        smpeg2.dll
libfreetype-6.dll    libvorbis-0.dll        zlib1.dll
Joels-MacBook-Pro:test joelcnz$ dirs
~/jpro/dpro2/OtherPeoples/Dgame/source/Dgame/test
Joels-MacBook-Pro:test joelcnz$ dub
Target derelict-util 1.9.1 is up to date. Use --force to rebuild.
Target derelict-sdl2 1.9.4 is up to date. Use --force to rebuild.
Target m3 0.0.6 is up to date. Use --force to rebuild.
Target derelict-gl3 1.0.12 is up to date. Use --force to rebuild.
Building dgame ~master configuration "main", build type debug.
Compiling using dmd...
4LU
16LU
64LU
80LU
8LU
20LU
8LU
8LU
32LU
Linking...
Running ./dgame-example
derelict.util.exception.SharedLibLoadException@../../../../.dub/packages/derelict-util-1.9.1/source/derelict/util/exception.d(35):
Failed to load one or more shared libraries:
    ../Frameworks/SDL2_image.framework/SDL2_image -
dlopen(../Frameworks/SDL2_image.framework/SDL2_image, 2): image not found
    /Library/Frameworks/SDL2_image.framework/SDL2_image -
dlopen(/Library/Frameworks/SDL2_image.framework/SDL2_image, 2): image not
found
    /System/Library/Frameworks/SDL2_image.framework/SDL2_image -
dlopen(/System/Library/Frameworks/SDL2_image.framework/SDL2_image, 2):
image not found
Error executing command run: Program exited with code 1

Joels-MacBook-Pro:test joelcnz$

**Comment by Dgame** [comment]
That's a derelict issue. Derelict tries to load the neccessary files by itself, as you can see here: https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/sdl.d#L42
For Mac you need *.dylib files, I deliver only *.dll files for Windows (only for 32 bit target because I compile mostly with dmd for 32 bit targets). So you need to build these files by yourself or take a look here: http://libsdl.org/download-2.0.php
There should be files for Mac and Windows, look at 'Development Libraries'.

I've described that in the install tutorial under 'Build Dgame'. But I should make that more visible.

**Comment by Dgame** [comment]
See also: http://derelictorg.github.io/using.html

**Comment by Dgame** [comment]
I've updated the install tutorial, hope it helps: http://dgame-dev.de/?page=tutorial&tut=installation

**Comment by joelcnz** [comment]
How come I don't need to install things like SDL2 with the Dlang UI library?

**Comment by Dgame** [comment]
I don't know, maybe they use static linking instead of dynamic. But it seems that on Linux you also need to install the SDL development files by yourself: https://github.com/buggins/dlangui#linux-builds

**Comment by Dgame** [comment]
I tested it on Ubuntu and I was right: you have to build/install SDL by yourself. It delivers (as Dgame) only *.dll files (for Win32).
