### ISSUE TITLE
Transparency fail

### ISSUE THREAD

**Issue by joelcnz** [Dgame/Dgame#37]
I set a colour for transparency, but it doesn't work on Dgame, (it works on other programs, like GIMP).

**Comment by Dgame** [comment]
Which part? Surface, Texture, Shape? Or do you mean the background?

**Comment by joelcnz** [comment]
Using the Spritesheet. It's not a big one, it works with the PNG files saved with GIMP.

**Comment by Dgame** [comment]
Can you post your code (and maybe your image)? That would help a lot to reproduce what is happening.

**Comment by joelcnz** [comment]
I don't think it's real problem. Looks like I can fix it with GIMP.

The attachment is the graphic which the transparency doesn't work for.

**Comment by Dgame** [comment]
Ok, keep me up to date.

**Comment by Dgame** [comment]
@joelcnz Could you solve the problem? Is it a problem with Dgame?

**Comment by joelcnz** [comment]
Looks like it happens with a curtain viewers saving an image (choose
transparency colour, and I click on which one I want). But it works with
GIMP alright, I don't feel I have to work around it. I don't think it's
worth fixing.

Another thing. Could you put in indexing with the sprite sheets. Access
each texture with a number. The thing there already doesn't work very well
and doesn't work hardly any way.

Just one other thing, this crashes the program.

Surface[string] sufs;
sufs["left"] = Suface("tankLeft.png");
sufs["right"] = Suface(tankRight.png");

**Comment by Dgame** [comment]
You can use ```setTextureRect``` and ```slideTextureRect```
Example: You image consist of your 'tankLeft' and 'tankRight' (the left tank is on the left part, the right tank on the right part of the image). Let us assume each of them has a size of 64x64 pixel. Now we declare a new Spritesheet ```Spritesheet s = new Spritesheet(your_texture, Rect(0, 0, 64, 64));```
Now you can move the rect over the image. First you will see the left part but after you called ```s.slideTextureRect();``` you will see the right part. And after a further call you will see (again) the left part.

**Comment by Dgame** [comment]
But indexing would be nice, too. Let me see what I can do this evening. ;)

**Comment by Dgame** [comment]
> Surface[string] sufs;
sufs["left"] = Suface("tankLeft.png");
sufs["right"] = Suface(tankRight.png");

I will investigate this. Thank you.

**Comment by Dgame** [comment]
Seems you've discovered a bug: http://forum.dlang.org/thread/bug-14321-3@https.issues.dlang.org%2F
and regarding indexing: http://dgame-dev.de/?package=graphic&module=Spritesheet#Spritesheet.selectFrame

Can this be closed?

**Comment by joelcnz** [comment]
Might want to be able to get the number of total frames.

I'd say, this issue can be closed.

**Comment by Dgame** [comment]
> Might want to be able to get the number of total frames.

I'll think about it. ;)

**Comment by joelcnz** [comment]
I don't think your, select frame, is working properly. I've got a 4 frames
sprite sheet, but I can't access the forth one, (with selectFrame).

Also, shouldn't the first frame number be 0, not 1.

One other thing. I think 'int' is cleaner (in a way), than ubyte. For
example: *selectFrame*(cast(ubyte)(idx + 1));

**Comment by Dgame** [comment]
Yeah, don't code at night... I'll fix that soon.

**Comment by Dgame** [comment]
Fixed
