### ISSUE TITLE
Loading Surface from file sometimes fails due to invalid file name string type

### ISSUE THREAD

**Issue by kr41** [Dgame/Dgame#40]
Loading Surface from file sometimes doesn't work.

```d
    /**
     * Load from filename. If any data is already stored, the data will be freed.
     */
    @nogc
    bool loadFromFile(string filename) nothrow {
        import std.file : exists;

        immutable bool ex = exists(filename);
        if (!ex) {
            print_fmt("File %s does not exists.\n", filename.ptr);
            return false;
        }

        SDL_FreeSurface(_surface); // free old surface

        _surface = IMG_Load(filename.ptr);
        if (!_surface) {
            print_fmt("Could not load image %s. Error: %s.\n", filename.ptr, SDL_GetError());
            return false;
        }
        
        assert(_surface.pixels, "Invalid pixel data.");

        return true;
    }
```

Take note, that `filename.ptr` is passed to `IMG_Load` function. `IMG_Load` is C function, so it operates zero-terminated strings. But D string is not zero-terminated. So if memory for a D string is allocated without trailing zero, `loadFromFile()` will not work. Here is the test:

```d
    string filenameWithTail = "samples/images/XS.png;trailing chars goes here";
    string cleanFilename = filenameWithTail[0..21];
    writefln("Clean filename is '%s'", cleanFilename);
    Surface invalidSurface = Surface(cleanFilename);
```

The output will be:

    Clean filename is 'samples/images/XS.png'
    Could not load image samples/images/XS.png;trailing chars goes here. Error: Couldn't open samples/images/XS.png;trailing chars goes here.

It usually works, because D compiler puts zero at the end of static strings. But if you get string from file, it won't. The fast fix is to use `toStringz` function from `std.string` module:

```d
        _surface = IMG_Load(filename.toStringz);
```

But it doesn't work with `@nogc` declaration of `loadFromFile()`. So I don't know how to fix it and keep this declaration.

**Comment by Dgame** [comment]
I've never had this issue but I will try to fix this even if it is very unlikely to happen. But the phobos version of toStringz is evil, It wasted your memory.

**Comment by Dgame** [comment]
I made my own toStringz method and fix all occurrences I've found. Thanks for reporting. ;)

**Comment by kr41** [comment]
Thank you!
