### ISSUE TITLE
[feature request] Sprite repeat.

### ISSUE THREAD

**Issue by whitebyte** [Dgame/Dgame#41]
I think one image worth 1000 words, so here it is:
![repeat](https://cloud.githubusercontent.com/assets/7704186/7429102/15738a06-f015-11e4-8b6c-3786d7d99aee.png)

Currently I don't see the easy way to implement this (quite common) effect with Dgame. Are there any plans on implementing it? I'm pretty new to D and OpenGL in general, so unfortunatenetly I can't make a proper PR at the moment.

**Comment by Dgame** [comment]
Did you tried [Texture.setRepeat](http://dgame-dev.de/?package=graphic&module=Texture#Texture.setRepeat)?

**Comment by whitebyte** [comment]
My bad, probably i've missed it.

**Comment by Dgame** [comment]
No problem, I'm glad it helps. :)
