### ISSUE TITLE
Incorrect tutorial guidance on limiting framerate.

### ISSUE THREAD

**Issue by rcorre** [Dgame/Dgame#48]
The [tutorial on limiting framerate](http://www.dgame-dev.de/?page=tutorial&tut=limit_framerate) suggests using the following:

```
if (sw.getTicks() >= TICKS_PER_FRAME) {
    // Do game logic
    // ...
    sw.reset();
}
```

I think this should actually be `sw.getElapsedTicks`, which would be zeroed out by `sw.reset`.
`sw.getTicks` will continue increasing, and after it reaches `TICKS_PER_FRAME` the first time will trigger the game logic on every pass.

**Comment by Dgame** [comment]
That's correct, thank you. I've fixed that right now.
