### ISSUE TITLE
rotate shape in vector direction

### ISSUE THREAD

**Issue by no-glue** [Dgame/Dgame#53]
how is it possible to rotate shape in vector direction? currently i have angle between position and velocity. i need object to be aligned with velocity vector.

**Comment by Dgame** [comment]
Per default, Dgame uses the top left corner as origin point. You can change that by calling setRotationCenter (which only affects the rotation origin) or by calling setOrigin (which changes the whole origin, so as well the position. Or did I misunderstand you?

**Comment by no-glue** [comment]
the end result should be moving object aligned with vector (and there are multiple objects). any idea how to do that? so for i tried setting rotation center at one vertex of an object but it not work. objects drift apart with time.

**Comment by Dgame** [comment]
I don't understand what you mean by "aligned with (a) vector". Could you give me an example?

**Comment by no-glue** [comment]
an example https://processing.org/examples/flocking.html. all objects are aligned (facing same direction) as their velocity vector.

**Comment by Dgame** [comment]
Ah, without overlaping, I see.  You could let them move in the same direction with your own offset between the objects. Wouldn't that be an option?

**Comment by no-glue** [comment]
yes i just need correct orientation.

**Comment by Dgame** [comment]
What's about setting the center of your object as rotation origin and use for all objects the same rotation direction?

**Comment by no-glue** [comment]
i was thinking the same thing. could not get it working with setRotationCenter. maybe it will work with setOrigin?

**Comment by Dgame** [comment]
What was the problem?

**Comment by no-glue** [comment]
i used left corner of an object as rotation center. this changes as object moves so objects were drifting apart too much.

**Comment by Dgame** [comment]
Try `getClipRect`or `getVertexRect`, that wil give you the surrounding rect. On this you can call `getCenter` to ascertain the center point of your object.

**Comment by Dgame** [comment]
I would suggest that you look at `atan2` for the rotation part.

**Comment by Dgame** [comment]
Did it work?

**Comment by no-glue** [comment]
yes it worked
