### ISSUE TITLE
Determine text size before drawing

### ISSUE THREAD

**Issue by opatut** [Dgame/Dgame#54]
In order to draw a dynamic text centered I would like to shift it by half its width to the left before drawing it.

However, currently the width of a text is only calculated upon drawing, hence, I will always receive the previous frame's text width as the "current" width of the text, even though I might have changed the contents and thus the text width.

A possible fix renders the text to a texture before returning the texture width, iff `_redraw` is true when the width is fetched. This should usually not lead to multiple render operations since the common order of updating text is

* `.setData`
* `.width` (render to texture!)
* `.setPosition`
* `.draw` (no re-render since `_redraw == false`)

Same goes for height, of course.

**Comment by Dgame** [comment]
That would destroy the const'ness of width and height. But I could offer the possibility to call a redraw/update method manually.

**Comment by Dgame** [comment]
Hope that is enough for your purpose.

**Comment by opatut** [comment]
While I pretty much dislike such unintuitive API, I guess there is no way around it... can't remove const'ness from width/height getters, of course.

What I've seen in other libs is things like `Font::getDimensions` or `Text::calculateBounds` or similar, which would not need to be const. However, that would mean 2 APIs (width/height + calculateBounds) for the same thing, which is of course another no-go.

I can't think of something that works well and gets the job done, sadly (except re-drawing every change, which is ridiculous :wink: ). So I guess going for `.update` would be best (I don't like "redraw" since it sounds like it should be called *after* `draw`, not before).

**Comment by opatut** [comment]
Preparing a PR right now :)

**Comment by Dgame** [comment]
Yes, sadly it is not the nicest choice, but the only one without massive intervention.

`Edit: damn, I've gotten slow :) Thanks for the quick fix!`
You're welcome. :)
