### ISSUE TITLE
small issue on page

### ISSUE THREAD

**Issue by bubnenkoff** [Dgame/Dgame#56]
"Or you can download them __here__ (See Runtime Binaries)."

On page: http://dgame-dev.de/index.php?controller=learn&mode=tutorial&version=0.6&tutorial=install
https://www.libsdl.org/download-2.0.ph
should be https://www.libsdl.org/download-2.0.php

**Comment by Dgame** [comment]
Thanks, I'll fix that immediately.

**Comment by Dgame** [comment]
Fixed
