### ISSUE TITLE
[Feature Request] A Window.draw overload with an offset

### ISSUE THREAD

**Issue by JackStouffer** [Dgame/Dgame#57]
Something like

```
Window.draw(Drawable d, Vector2f offset)
```

where calling it would make this draw happen at `(d.x + offset.x, d.y + offset.y)`. This would make a player camera and multiple cameras in a level much easier to implement. Inspired by Love2D's [love.graphics.translate](https://love2d.org/wiki/love.graphics.translate).

**Comment by Dgame** [comment]
Why not using the move method from e.g. the Sprite?
If you want to implement a Camera without moving the Sprites: the `projection` member of the Window class is intentionally public:
[Member](https://github.com/Dgame/Dgame/blob/master/source/Dgame/Window/Window.d#L114) and [loading method](https://github.com/Dgame/Dgame/blob/master/source/Dgame/Window/Window.d#L193)

**Comment by JackStouffer** [comment]
> Why not using the move method from e.g. the Sprite?

Convenience, and I'm also drawing basic shapes and vertex arrays which don't supply a `move` method.

> If you want to implement a Camera without moving the Sprites: the projection member of the Window class is intentionally public:

I'll look into this, thanks. If this does not work for me I'll reopen this.

**Comment by JackStouffer** [comment]
With your suggestion, I was able to come up with the code below, thanks. Maybe it could be added to the tutorials on the website?

```
struct Camera {
    private Window *window;
    private Matrix4x4 original;
    private Vector3f eye = Vector3f(0, 0, 1);
    private Vector3f look = Vector3f(0, 0, 0);
    private Vector3f up = Vector3f(0, 1, 0);

    this(ref Window window) {
        this.window = &window;
        this.original = this.window.projection;
    }

    void moveToPosition()(float x, float y) {
        // Keep the camera in the level
        if (x < 0)
            x = 0;
        if (y < 0)
            y = 0;
        if (x > (MAP_WIDTH * TILE_SIZE) - WINDOW_WIDTH)
            x = (MAP_WIDTH * TILE_SIZE) - WINDOW_WIDTH;
        if (y > (MAP_HEIGHT * TILE_SIZE) - WINDOW_HEIGHT)
            y = (MAP_HEIGHT * TILE_SIZE) - WINDOW_HEIGHT;

        // reset
        this.window.projection = this.original;

        eye.x = x;
        eye.y = y;
        look.x = x;
        look.y = y;

        this.window.projection.lookAt(eye, look, up);
        this.window.loadProjection();

        return;
    }

    void moveToPosition()(Vector2f v) {
        moveToPosition(v.x, v.y);
    }
}
```

**Comment by Dgame** [comment]
I would not copy the whole Matrix, since it is has a size of `16 * float.sizeof (=4 byte)` = 64 Byte. But besides that it looks nice. I have currently not that much time, so, if you would write the tutorial it would be there much quicker. :)
