### ISSUE TITLE
Dgame Does not render on multiple windows

### ISSUE THREAD

**Issue by Jackoz530** [Dgame/Dgame#58]
Hello, so I've been experimenting with the framework and I tried to implement a game that has more than two windows.

The first window is the main game and the second window is a smaller one with the various commands you can select.

So I tried to render sprites onto the first window and the second window, and failed.

---

window_1.clear();
window_2.clear();
window_1.draw(sprite_1);
window_2.draw(sprite_2);
window_1.display();
window_2.display();

So far, when two windows are called to clear, draw and display, it didn't render anything. There was no error message, but once I commented out the window_2 calls, it rendered the first window without flaw.

So are multiple windows supported here?

**Comment by Dgame** [comment]
Yes, it should work. I'll examine it this afternoon.

**Comment by Jackoz530** [comment]
I just discovered that when I just commented out just the window_2 render calls, the problem still persists, but when I commented out the initialization of the window_2, window_1 was rendering fine.
Code example:

Window window_1 = new Window(640,480,"Window_1");
Window window_2 = new Window(200,200,"Window_2");
window_1.clear();
//window_2.clear();
window_1.draw(sprite_1);
//window_2.draw(sprite_2);
window_1.display();
//window_2.display();
//Problem still persists

**Comment by Dgame** [comment]
I'm sorry, but after many attempts, I can only assume that the SDL has a problem with the manual OpenGl calls (see the draw methods in Window.d). Therefore (as I presume) context switching is not successful. My time is still limited (until January), but if you find out more information, let me know.
