### ISSUE TITLE
Necessary code doesn't execute when compiling in release mode

### ISSUE THREAD

**Issue by pineapplemachine** [Dgame/Dgame#60]
One of the more blatant offenders is line 155 in Window.d: `assert(SDL_GL_MakeCurrent(_window, _glContext) == 0);`

Assertions are not evaluated when compiling in release mode. https://dlang.org/spec/contracts.html#assert_contracts

Lines like this should throw errors upon failure instead of using `assert`.

**Comment by Dgame** [comment]
Well seen, thank you. I'll try to fix that until the end of the week. Unfortunately, I'm a little busy right now.

**Comment by pineapplemachine** [comment]
I went to do a bit of it myself and learned that using @nogc complicates constructing and throwing errors. This problem may not have a simple solution.

http://forum.dlang.org/post/luvoo1$b6a$1@digitalmars.com
https://w0rp.com/blog/post/writing-exceptional-nogc-code/

**Comment by Dgame** [comment]
Right, I have forgotten this... In this case I will leave it as it is. I believe, if some error occurred, everyone will most certainly try to run his application in the debug mode.
