### ISSUE TITLE
Shape color is being changed by unrelated objects

### ISSUE THREAD

**Issue by DreadKyller** [Dgame/Dgame#61]
I create in the code below, 1 shape with Geometry.Quads, Then I create a Surface, Texture and a Sprite. The texture has a color of orange as it's base color.

I do not call setTexture() on the shape. The following occurs:

- If I do not render the sprite, the shape becomes orange even though I set its color to Color4b.White
- If I render the sprite before rendering the shape the shape renders white, as it should.
- If I render the sprite after rendering the shape the shape also renders white

So it seems that for some reason, if I create a sprite and don't render it, it affects the other objects in the scene somehow.

```
void main() {
    Window wnd = Window(640, 480, "Dgame Test");
	
    wnd.setClearColor(Color4b.Black);
    
    Shape fightbox = new Shape(Geometry.Quads,
        [
            Vertex(50  , 50 ),
            Vertex(200 , 50 ),
            Vertex(200 , 200),
            Vertex(50  , 200)
        ]
    );
    fightbox.fill = Shape.Fill.Line;
    fightbox.setColor(Color4b.White);
    fightbox.lineWidth = 4;
    
    Surface test_surface = Surface("sprites/test_img");
    Texture test_texture = Texture(test_surface);
    
    test_sprite = new Sprite(test_texture);
    test_sprite.setPosition(50, 100);
    
    Event event;
    while (Status.isRunning) {
        wnd.clear();
        
        while (wnd.poll(&event)) {
        	handleEvent(event);
        }
        if(Keys.isKeyDown(Keyboard.Key.Esc))
        {
        	Status.isRunning = false;
        }
        auto vect = wnd.getPosition();
        
        if(Keys.isKeyDown(Keyboard.Key.F))
        {
        	writeln("Window Position = x(",vect.x, "), y(",vect.y,")");
        }
        
        //wnd.draw(test_sprite); // #1
        wnd.draw(fightbox);// #2
        //wnd.draw(test_sprite); // #3
        
        wnd.display();
    }
```
With either #1 or #3 un-commented the shape displays white, if both are commented the shape appears orange (the color of the image). Nothing else besides commenting or un-commenting those 3 statements are changed.

Without rendering the sprite:
![without_sprite_render](https://cloud.githubusercontent.com/assets/788657/15055630/8c743828-12db-11e6-999d-6f9ccec26f51.png)

With rendering the sprite:
![with_sprite_render](https://cloud.githubusercontent.com/assets/788657/15055643/9c332012-12db-11e6-832c-44ad535499c9.png)

It should also be noted that this issue only occurs if the sprite has transparency, tested with a solid sprite without transparency and no issue at all.

Edit, additional information:
- Dgame 0.6.3 from DUB

Edit 2, some more testing:
- It I placed the wnd.draw(test_sprite) inside an if statement for if the G key is held down, then i got the following results:
 - At first, upon program loading, the shape appeared orange
 - While holding the "G" key the sprite appeared and the shape went white
 - After letting go of the "G" key the sprite disapeared, and the box did *not* return to orange, instead it remained white.
 - As soon as the sprite renders once the bug is gone.

Edit 3, Found some more info:
- After some testing, I have confirmed that the color of the shape is the top-left pixel of the texture.

**Comment by Dgame** [comment]
Interesting. I assume it's because of [this](https://github.com/Dgame/Dgame/blob/master/source/Dgame/Window/Window.d#L692).
I'm using `glPush`and `glPop`in [Shape](https://github.com/Dgame/Dgame/blob/master/source/Dgame/Graphic/Shape.d#L64), but, as you can see, there is nothing like that in [Sprite](https://github.com/Dgame/Dgame/blob/master/source/Dgame/Graphic/Sprite.d#L53). I will look into this on Saturday and if that is the culprit it will be fixed until evening.

**Comment by DreadKyller** [comment]
I edited my comment, the last Edit part at the bottom of the page may be informative.

**Comment by Dgame** [comment]
Hm, that sounds strange. Where comes the orange color? :confused: Looks like it wont be that simple.

**Comment by DreadKyller** [comment]
I think the orange color comes from the sprite texture, to test and be sure I will change the color of the sprite and get back to you if the color of the shape changes.

**Comment by Dgame** [comment]
Problem was, that the Texture was often still bound after using.
