### ISSUE TITLE
TTF_Init is not being called, formatting Text always errors "Font Invalid"

### ISSUE THREAD

**Issue by DreadKyller** [Dgame/Dgame#62]
I have loaded a Font object and a text object with said Font. When i go to use text.format(Args...) I am presented with "Font is invalid".

After a little research i decided to manually import derelict.sdl2.ttf myself and call TTF_Init()

After doing so I no longer got the error. Maybe something as simple as a static boolean somewhere for if TTF has been initialized, and upon a new Font being instantiated check that boolean and call TTF_Init when the first font is created.

This is a minor issue, but it does make following the tutorial impossible (as the tutorial doesn't include manually calling TTF_Init() and thusly errors)

Dgame Version = 0.6.3

**Comment by Dgame** [comment]
Which dmd version? I'm pretty sure you use `2.071`, right? ;)

**Comment by Dgame** [comment]
I need some example code, my old test code still works.

**Comment by Dgame** [comment]
TTF_Init is (as I thought) called in [Internal/Init.d](https://github.com/Dgame/Dgame/blob/master/source/Dgame/Window/Internal/Init.d#L106), which is called [here](https://github.com/Dgame/Dgame/blob/master/source/Dgame/Window/Window.d#L141). So, as long as you initialized a Window before using the Text/Font, it should work.

**Comment by Dgame** [comment]
That's the last bug for now. If you can confirm, that it is runnable after you initialized a Window, I will close this issue and tag a new release.

**Comment by DreadKyller** [comment]
I literally can copy the tutorial code and it still occurs for me.

```
static void init(Window *_wnd)
{
	wnd = _wnd;
	fps_font = Font("fonts/arial.ttf", 22);
	fps_text = new Text(fps_font);

	box= new Shape(Geometry.Quads,
	[
		Vertex(Zones.primary.x - (Zones.primary.w/2), Zones.primary.y),
		Vertex(Zones.primary.x + (Zones.primary.w/2), Zones.primary.y),
		Vertex(Zones.primary.x + (Zones.primary.w/2), Zones.primary.y+Zones.primary.h),
		Vertex(Zones.primary.x - (Zones.primary.w/2), Zones.primary.y+Zones.primary.h)
	]
	);
	box.fill = Shape.Fill.Line;

	box.setColor(Color4b.White);
	box.lineWidth = 4;
}
```
That method is in an initialization method for a class in my project called "Engine". The init method takes a pointer to the Window object, and thusly the Window object is created before this method is called. The font is in the correct place, and works if I manually call TTF_Init().

I am using: DMD 2.071
