### ISSUE TITLE
StopWatch Divide by 0 when trying to fill frame_ms

### ISSUE THREAD

**Issue by DreadKyller** [Dgame/Dgame#63]
There's a bug in StopWatch. If you set frame_ms to a non-null value, to fill the frame_ms variable, you get a Divide by Zero error. The code below is from your GitHub source. I added some comments to show where the problem is.

```
@nogc
uint getCurrentFPS(uint* frame_ms = null) nothrow {
    immutable uint elapsed_ticks = this.getElapsedTicks();
    if (elapsed_ticks >= 1000) {
        _currentFps = _numFrames;
        _numFrames = 0;// When this if statement operates, _numFrames is set to 0
        this.reset();
    }

    if (frame_ms)
        *frame_ms = elapsed_ticks / _numFrames;// _numFrames was just set to 0 above
    _numFrames++;

    return _currentFps;
}
```
You could create a local variable and use that instead.

```
@nogc
uint getCurrentFPS(uint* frame_ms = null) nothrow {
    immutable uint elapsed_ticks = this.getElapsedTicks();
    uint _numFramesLocal = _numFrames;
    if (elapsed_ticks >= 1000) {
        _currentFps = _numFrames;
        _numFrames = 0;
        this.reset();
    }

    if (frame_ms)
        *frame_ms = elapsed_ticks / _numFramesLocal;// Still has the value from before the reset
    _numFrames++;

    return _currentFps;
}
```
_numFrames is not incremented during the point between the local variable create and use, so it always holds the same value that _numFrames would have if it hadn't been set to 0. There is another way to solve this issue, and that is to just rearrange the method a bit:

```
@nogc
uint getCurrentFPS(uint* frame_ms = null) nothrow {
    immutable uint elapsed_ticks = this.getElapsedTicks();

    if (frame_ms)
        *frame_ms = elapsed_ticks / _numFrames;
    
    if (elapsed_ticks >= 1000) {
        _currentFps = _numFrames;
        _numFrames = 0;
        this.reset();
    }
    _numFrames++;
    
    return _currentFps;
}
```

Sorry for so many frequent Issues, but I'm using your library extensively and am finding a lot of problems.

**Comment by Dgame** [comment]
Oh, that is a rookie mistake. Sorry. :D

>Sorry for so many frequent Issues, but I'm using your library extensively and am finding a lot of problems.

Never mind, that's why I published it on Github. Each fixed bug will make Dgame a bit better.
