### ISSUE TITLE
DerelictGL3 not able to find symbol ( glGetnTexImage )

### ISSUE THREAD

**Issue by DreadKyller** [Dgame/Dgame#64]
The symbol glGetnTexImage was added with GL4.5. A while ago I had no issue with this, however recently (without even updating DGame, did a dependency change?) I suddenly get this error any time I create a Window.

Appearently the error is caused by my graphics cards max driver version for OpenGL being below 4.5. But apparently it's trying to use version 4.5 when I don't have said version for my system. The suggested solution is to use DerelictGL3.reload(GLVersion.None, GLVersion.GL44), however this is not possible to do before creating a new Window, because it requires an OpenGL context to exist, and if I do it after creating the window then I get the error before I have a chance to tell it to not try loading that version.

I'm not exactly sure what can be done about this issue, as it's really been infuriating me for a few months now. I've tried many times to figure this out myself and it's not working.

In the error log, the last trace within your code is:
AppData\Roaming\dub\packages\dgame-0.6.4\source\Dgame\Window\Internal\Init.d(192)

`immutable GLVersion glver = DerelictGL.reload();`

Maybe allow some way to allow users to pass in maximum version to use in the reload command, or something?

**Comment by Dgame** [comment]
Have you already tried to declare the gl version in the [GLContextSettings](https://github.com/Dgame/Dgame/blob/master/source/Dgame/Window/GLContextSettings.d)? It might help.

**Comment by Dgame** [comment]
Just to be sure, here is the link to the corresponding tutorial: http://dgame-dev.de/index.php?controller=learn&mode=tutorial&version=0.6&tutorial=gl_settings

**Comment by DreadKyller** [comment]
Thank you, that does indeed fix the issue, setting to Version.GL44 fixes the problem, thanks.
