### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by leotada** [Dgame/Dgame#66]
Dgame could have collision detection :)

**Comment by Dgame** [comment]
It has: https://github.com/Dgame/Dgame/blob/master/source/Dgame/Math/Rect.d#L190
It's limited to bounding boxes, but I'm open for other approaches.

**Comment by leotada** [comment]
Cool, if I learn it, could help with.

**Comment by leotada** [comment]
A example, but with sprites: https://github.com/SFML/SFML/wiki/Source:-Simple-Collision-Detection

**Comment by leotada** [comment]
Circle collision with circle: https://github.com/Dgame/Dgame/pull/68
